import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.js
import { GeistProvider, CssBaseline } from '@geist-ui/react';

export default function RootLayout({ children }) {
  return (
    <html lang="en"> {/* Ensure lang attribute is present */}
      <head>
        <title>Your App Title</title>
        {/* Add any meta tags, external links or stylesheets here */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GeistProvider>
          <CssBaseline />
          {children}
        </GeistProvider>
      </body>
    </html>
  );
}

